src/Entity/Message.php
<?php

namespace App\Entity;

use App\Repository\MessageRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=MessageRepository::class)
 */
class Message
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read = 0;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="sent")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="received")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipient;

    public function __construct(){
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Form/MessageType.php
<?php

namespace App\Form;


use App\Entity\Message;
use App\Entity\User;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessageType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $contacts = $options["contacts"];
      
        $builder
            ->add('title', TextType::class, [
                "attr" => [
                    "class" => "form-control"
                ],
                "label" => "Titre"
            ])
            ->add('message', TextareaType::class, [
                "attr" => [
                    "class" => "form-control"
                ], 
                "label" =>"Message"
            ])
            ->add("recipient", EntityType::class, [
                'class' => User::class,
                "choices"=> $contacts,
                'choice_label' => 'pseudo',
                "attr" => [
                    "class" => "form-control"
                ], 
                "label" => "Destinataire"
            ])
            ->add('envoyer', SubmitType::class, [
                "attr" => [
                    "class" => "btn btn-success"
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
            'contacts'=>null
        ]);
    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Entity\Message;
use App\Form\MessageType;
use App\Form\MessageResponseType;
use App\Repository\MessageRepository;
use App\Repository\MissionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MessagesController extends AbstractController
{
    /**
     * @Route("/messages", name="messages")
     */
    public function index()
    {
        return $this->render('messages/index.html.twig', [
            'controller_name' => 'MessagesController',
        ]);
    }

    /**
     * @Route("/envoyer", name="send")
     */
    public function send(Request $request, EntityManagerInterface $manager, MissionRepository $missionRepository) : Response{

        $message = new Message;

        $user_id = $this->getUser()->getId();

        $matchingMissions = $missionRepository
        ->findContacts($user_id);

        $contacts = [];

        foreach($matchingMissions as $mission){

            $contacts[]=$mission->getBeneficiary();
        }
        
        $form = $this->createForm(MessageType::class, $message, array('contacts' => $contacts));

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $message->setSender($this->getUser());
            $manager->persist($message);
            $manager->flush();

            $this->addFlash("message", "Votre message a bien été envoyé.");
            return $this->redirectToRoute("messages");
        }

        return $this->render("messages/send.html.twig", [
            "form" => $form->createView()
        ]);
    }

    /**
     * @Route("/lire/{id}", name="read")
     */
    public function read(EntityManagerInterface $manager, MessageRepository $messageRepository, $id) : Response{

        $message = $messageRepository
        ->findOneBy(
            ['id' => $id]
        );

        $message->setIsRead(true);
        $manager->persist($message);
        $manager->flush();

        return $this->render('messages/messageDetails.html.twig', [
            "message" => $message
        ]);
    }

     /**
     * @Route("/supprimer/{id}", name="delete")
     */
    public function delete(EntityManagerInterface $manager,MessageRepository $messageRepository, $id) : Response{

        $message = $messageRepository
        ->findOneBy(
            ['id' => $id]
        );

        $manager->remove($message);
        $manager->flush();

        return $this->redirectToRoute("messages");
    }

    /**
     * @Route("/répondre/{id}", name="response")
     */
    public function reply(MessageRepository $mr, EntityManagerInterface $em, Request $request, $id){

        $user = $this->getUser();

        $repliedMessage = $mr
        ->findOneBy(
            ["id" => $id]
        );

        $message = new Message();

        $recipient = $repliedMessage->getSender();
        $recipient_pseudo = $repliedMessage->getSender()->getPseudo();

        $form = $this->createForm(MessageResponseType::class, $message);
    
        $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        
        $message->setRecipient($recipient);
        $message->setCreatedAt(new \DateTime());
        $message->setIsRead(0);
        $message->setSender($user);

        $em->persist($message);
        $em->flush();

        $this->addFlash('success', 'Votre réponse a été envoyée.');
        
            return $this->redirectToRoute('messages');
    } 
        return $this->render('messages/replyTo.html.twig',
            ['form'=> $form->createView(),
            'recipient' => $recipient_pseudo
        ]);
    }


}

templates/messages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}
 
{% block body %}

<div class="container">
    <div class="row">
        <div class="col">
            <h1>Messagerie</h1>
            <div class="center">
                <a href="{{ path("send")}}" id="sendMessage" class="btn btn-success">Envoyer un message</a>
            </div>
            <ul class="nav nav-tabs justify-content-around" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active" id="received-tab" data-bs-toggle="tab" data-bs-target="#received" type="button" role="tab" aria-controls="received" aria-selected="true">Boîte de réception</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="sent-tab" data-bs-toggle="tab" data-bs-target="#sent" type="button" role="tab" aria-controls="sent" aria-selected="false">Messages envoyés</button>
                </li>
            </ul>

            <div class="tab-content">

                <div class="tab-pane fade show active" id="received" role="tabpanel" aria-labelledby="received-tab">
                    <div class="row head">
                        <div class="col">De</div>
                        <div class="col">Sujet</div>
                        <div class="col hide">Date</div>
                        <div class="col hide">Contenu</div>
                        <div class="col text-center">Action</div>
                    </div>
                        {% for message in app.user.received %}
                            {% if message.isRead == 0 %}
                                {% set bold = "fw-bold" %}
                            {% else %}
                                {% set bold = "" %}
                            {% endif %}
                                <div class="row message">
                                    <div class="messageLine col {{bold}} ">{{ message.sender.pseudo}}</div>
                                    <div class="messageLine col {{bold}}" >
                                        <a class="messageSubject" href="{{path("read", {id:message.id})}}">{{ message.title}}</a>
                                    </div>
                                    <div class="messageLine col hide {{bold}}">{{ message.createdAt  | date('d/m/Y') }}</div>
                                    <div class="messageLine col  hide {{bold}}">{{ message.message}}</div>
                                    <div class="messageLine text-center col actionLinks {{bold}}">
                                        <a href="{{ path("response", {id:message.id})}}">
                                            <img class="edit" src="/img/edit.png" width='35d'/>
                                        </a>
                                        <a href="{{ path("delete", {id:message.id})}}">
                                            <img class="bin" src="/img/trash.png" width='35'/>
                                        </a>
                                    </div>
                                </div>
                        {% endfor %}
                </div>
                <div class="tab-pane fade" id="sent" role="tabpanel" aria-labelledby="sent-tab">
                    <div class="row head">
                        <div class="col">A</div>
                        <div class="col">Sujet</div>
                        <div class="col hide ">Date</div>
                        <div class="col hide">Contenu</div>
                        <div class="col text-center">Action</div>
                    </div>
                        {% for message in app.user.sent %}
                            <div class="row message">
                                <div class="messageLine col">{{ message.recipient.pseudo}}</div>
                                <div class="messageLine col">
                                    <a class="messageSubject" href="{{path("read", {id : message.id})}}">{{ message.title}}</a>
                                </div>
                                <div class="messageLine col hide">{{ message.createdAt|date('d/m/Y')}}</div>
                                <div class="messageLine col hide">{{ message.message}}</div>
                                <div class="messageLine text-center col actionLinks">
                                    <a href="{{ path("delete", {id : message.id})}}">
                                        <img class="bin" src="/img/trash.png" width='35'/></a>
                                </div>
                            </div>
                        {% endfor %}
                </div>
            </div>

        </div>
    </div>    
</div>
{% endblock %}

templates/messages/messageDetails.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}
 
{% block body %}

<div class="container">
    <div class="row">
            <h1>Détails du message</h1>
    </div>
</div>

<div class="container">
    <div class="jumbotron">

            <h1 class="display-4 text-center">{{ message.title}}</h2>
            <p class="lead">Message de {{ message.sender.pseudo}}</p>
            <p class="lead">Le {{ message.createdAt | date('d/m/Y') }}</p>
            <div> {{ message.message }} </div>
            <hr class="my-4">
            <div class="container text-center">
               {#  <a  href="{{ path("response")}}" class="btn btn-success">Répondre</a> #}
            </div>
    </div>
</div>

<div class="container text-center">
    <a href="{{ path("messages")}}" class="btn btn-success">Retour à la boite de réception</a>
</div>

{% endblock %}

templates/messages/replyTo.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}
 
{% block body %}

<div class="container">
    <div class="row">
        <div class="col">
            <h1>Répondre à {{recipient}} </h1>
            {{ form(form)}}
          
        </div>
    </div>
</div>
{% endblock %}

templates/messages/send.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie{% endblock %}
 
{% block body %}

<div class="container">
    <div class="row">
        <div class="col">
            <h1>Envoyer un message</h1>
            {{ form(form)}}
          
        </div>
    </div>
</div>
{% endblock %}